version: "3"
services:
  server:
    tty: true
    stdin_open: true
    image: node:alpine
    container_name: chapterZ-dev
    volumes:
      - "/var/www/chapter-z-website:/code"
    networks: 
      - chapterZ
    command: sh -c "cd /code && npm install && npm start"
networks:
  chapterZ:
    external: true