version: "3"
services:
  server:
    tty: true
    stdin_open: true
    image: node:alpine
    container_name: chapterZ
    volumes:
      - "/var/www/chapter-z-website:/code"
    networks: 
      - chapterZ
    command: sh /code/buildAndRun.sh
networks:
  chapterZ:
    external: true