version: "3"
services:
  server:
    tty: true
    stdin_open: true
    image: registry.gitlab.com/tstark2/chapter-z-website/server:1.0.10
    container_name: chapterZ-node
    volumes:
      - "/Users/todd/Documents/Projects/chapter-z-website/.env:/var/www/.env"
    ports:
      - 32405:80
